import { Resource } from '@ngx-batatas/engine';
import { ResourceNames } from './resources.names';

export const STORY_RESOURCES: Resource[] = [
  {
    id: ResourceNames.backAirplane,
    type: 'background',
    tags: ['airplane'],
    path: '/assets/resources/new-game/back.airplane.jpg',
  },
  {
    id: ResourceNames.backBedroom,
    type: 'background',
    tags: ['bedroom'],
    path: '/assets/resources/new-game/back.bedroom.jpg',
  },
  {
    id: ResourceNames.backCabin,
    type: 'background',
    tags: ['cabin'],
    path: '/assets/resources/new-game/back.cabin.jpg',
  },
  {
    id: ResourceNames.backCabinFly,
    type: 'background',
    tags: ['cabin', 'fly'],
    path: '/assets/resources/new-game/back.cabin_fly.png',
  },
  {
    id: ResourceNames.backCristLxClose,
    type: 'background',
    tags: ['crist-lx-close'],
    path: '/assets/resources/new-game/back.crist-lx-close.jpg',
  },
  {
    id: ResourceNames.backCristLx,
    type: 'background',
    tags: ['crist-lx'],
    path: '/assets/resources/new-game/back.crist-lx.jpg',
  },
  {
    id: ResourceNames.backLivingRoom,
    type: 'background',
    tags: ['living', 'room'],
    path: '/assets/resources/new-game/back.living_room.png',
  },
  {
    id: ResourceNames.backLxCaisTejo,
    type: 'background',
    tags: ['lxcaistejo'],
    path: '/assets/resources/new-game/back.lxCaisTejo.jpg',
  },
  {
    id: ResourceNames.portraitAngelaWhiteNaked,
    type: 'image',
    tags: ['angela-white'],
    path: '/assets/resources/new-game/portrait.angela-white.naked.png',
  },
  {
    id: ResourceNames.portraitAngelaWhite,
    type: 'image',
    tags: ['angela-white'],
    path: '/assets/resources/new-game/portrait.angela-white.png',
  },
  {
    id: ResourceNames.portraitDanteCole,
    type: 'image',
    tags: ['dante-cole'],
    path: '/assets/resources/new-game/portrait.dante-cole.png',
  },
  {
    id: ResourceNames.portraitKhalifa,
    type: 'image',
    tags: ['khalifa'],
    path: '/assets/resources/new-game/portrait.khalifa.png',
  },
  {
    id: ResourceNames.portraitPilot,
    type: 'image',
    tags: ['pilot'],
    path: '/assets/resources/new-game/portrait.pilot.png',
  },
  {
    id: ResourceNames.soundAirplane,
    type: 'sound',
    tags: ['airplane'],
    path: '/assets/resources/new-game/sound.airplane.mp3',
  },
  {
    id: ResourceNames.soundSexWoman1,
    type: 'sound',
    tags: ['sex', 'woman'],
    path: '/assets/resources/new-game/sound.sex_woman.1.mp3',
  },
  {
    id: ResourceNames.videoAngelaWhiteDog1,
    type: 'video',
    tags: ['angela-white'],
    path: '/assets/resources/new-game/video.angela-white.dog1.mp4',
  },
  {
    id: ResourceNames.videoBiBlowjob,
    type: 'video',
    tags: ['bi', 'blowjob'],
    path: '/assets/resources/new-game/video.bi_blowjob.mp4',
  },
  {
    id: ResourceNames.videoBiBlowjobStand,
    type: 'video',
    tags: ['bi', 'blowjob', 'stand'],
    path: '/assets/resources/new-game/video.bi_blowjob_stand.mp4',
  },
  {
    id: ResourceNames.videoBiLickReverserCowgirld,
    type: 'video',
    tags: ['bi', 'lick', 'reverser-cowgirld'],
    path: '/assets/resources/new-game/video.bi_lick_reverser-cowgirld.mp4',
  },
  {
    id: ResourceNames.videoBlowjobAngelaWhite,
    type: 'video',
    tags: ['blowjob', 'angela-white'],
    path: '/assets/resources/new-game/video.blowjob_angela-white.mp4',
  },
  {
    id: ResourceNames.videoBlowjobDanteCole,
    type: 'video',
    tags: ['blowjob', 'dante-cole'],
    path: '/assets/resources/new-game/video.blowjob_dante-cole.mp4',
  },
  {
    id: ResourceNames.videoCumTitsAngelaWhite,
    type: 'video',
    tags: ['cum', 'tits', 'angela', 'white'],
    path: '/assets/resources/new-game/video.cum_tits_angela_white.mp4',
  },
  {
    id: ResourceNames.videoCumTreesomeTits,
    type: 'video',
    tags: ['cum', 'treesome', 'tits'],
    path: '/assets/resources/new-game/video.cum_treesome_tits.mp4',
  },
  {
    id: ResourceNames.videoDoggyDanteCole,
    type: 'video',
    tags: ['doggy', 'dante-cole'],
    path: '/assets/resources/new-game/video.doggy_dante-cole.mp4',
  },
  {
    id: ResourceNames.videoDoggyStrapOnAssAngelaWhite,
    type: 'video',
    tags: ['doggy', 'strap-on', 'ass', 'angela', 'white'],
    path: '/assets/resources/new-game/video.doggy_strap-on_ass_angela_white.mp4',
  },
  {
    id: ResourceNames.videoDogStyleFront,
    type: 'video',
    tags: ['dog', 'style', 'front'],
    path: '/assets/resources/new-game/video.dog_style_front.mp4',
  },
  {
    id: ResourceNames.videoFuckAngelaWhiteDoggyPov,
    type: 'video',
    tags: ['fuck', 'angela', 'white', 'doggy', 'pov'],
    path: '/assets/resources/new-game/video.fuck_angela_white_doggy_pov.mp4',
  },
  {
    id: ResourceNames.videoMaleFingerPussy1,
    type: 'video',
    tags: ['male', 'finger', 'pussy1'],
    path: '/assets/resources/new-game/video.male_finger_pussy1.mp4',
  },
  {
    id: ResourceNames.videoMaleFingerPussy2,
    type: 'video',
    tags: ['male', 'finger', 'pussy2'],
    path: '/assets/resources/new-game/video.male_finger_pussy2.mp4',
  },
  {
    id: ResourceNames.videoMaleFingerPussyOrgasm,
    type: 'video',
    tags: ['male', 'finger', 'pussy', 'orgasm'],
    path: '/assets/resources/new-game/video.male_finger_pussy_orgasm.mp4',
  },
  {
    id: ResourceNames.videoMaleWankMale1,
    type: 'video',
    tags: ['male', 'wank', 'male1'],
    path: '/assets/resources/new-game/video.male_wank_male1.mp4',
  },
  {
    id: ResourceNames.videoMaleWankMale2,
    type: 'video',
    tags: ['male', 'wank', 'male2'],
    path: '/assets/resources/new-game/video.male_wank_male2.mp4',
  },
  {
    id: ResourceNames.videoMaleWankMaleOrgasm,
    type: 'video',
    tags: ['male', 'wank', 'male', 'orgasm'],
    path: '/assets/resources/new-game/video.male_wank_male_orgasm.mp4',
  },
  {
    id: ResourceNames.videoManLickAngelaWhite,
    type: 'video',
    tags: ['man', 'lick', 'angela', 'white'],
    path: '/assets/resources/new-game/video.man_lick_angela_white.mp4',
  },
  {
    id: ResourceNames.videoManLickAngelaWhiteOrgasm,
    type: 'video',
    tags: ['man', 'lick', 'angela', 'white', 'orgasm'],
    path: '/assets/resources/new-game/video.man_lick_angela_white_orgasm.mp4',
  },
  {
    id: ResourceNames.videoManLickTits,
    type: 'video',
    tags: ['man', 'lick', 'tits'],
    path: '/assets/resources/new-game/video.man_lick_tits.mp4',
  },
  {
    id: ResourceNames.videoMasturbateDickPants,
    type: 'video',
    tags: ['masturbate', 'dick', 'pants'],
    path: '/assets/resources/new-game/video.masturbate_dick_pants.mp4',
  },
  {
    id: ResourceNames.videoMasturbatePussyPants,
    type: 'video',
    tags: ['masturbate', 'pussy', 'pants'],
    path: '/assets/resources/new-game/video.masturbate_pussy_pants.mp4',
  },
  {
    id: ResourceNames.videoMissLickPussyAngelaWhite,
    type: 'video',
    tags: ['miss', 'lick', 'pussy', 'angela', 'white'],
    path: '/assets/resources/new-game/video.miss_lick_pussy_angela_white.mp4',
  },
  {
    id: ResourceNames.videoMissPovAngelaWhite,
    type: 'video',
    tags: ['miss', 'pov', 'angela', 'white'],
    path: '/assets/resources/new-game/video.miss_pov_angela_white.mp4',
  },
  {
    id: ResourceNames.videoMissPovAngelaWhiteOrgasm,
    type: 'video',
    tags: ['miss', 'pov', 'angela', 'white', 'orgasm'],
    path: '/assets/resources/new-game/video.miss_pov_angela_white_orgasm.mp4',
  },
  {
    id: ResourceNames.videoPovMan1,
    type: 'video',
    tags: ['pov', 'man', '1'],
    path: '/assets/resources/new-game/video.pov_man_1.mp4',
  },
  {
    id: ResourceNames.videoPovMan2,
    type: 'video',
    tags: ['pov', 'man', '2'],
    path: '/assets/resources/new-game/video.pov_man_2.mp4',
  },
  {
    id: ResourceNames.videoPovManOrgasm,
    type: 'video',
    tags: ['pov', 'man', 'orgasm'],
    path: '/assets/resources/new-game/video.pov_man_orgasm.mp4',
  },
  {
    id: ResourceNames.videoRimjobAngelaWhite,
    type: 'video',
    tags: ['rimjob', 'angela', 'white'],
    path: '/assets/resources/new-game/video.rimjob_angela_white.mp4',
  },
  {
    id: ResourceNames.videoWomanLickAngelaWhite,
    type: 'video',
    tags: ['woman', 'lick', 'angela', 'white'],
    path: '/assets/resources/new-game/video.woman_lick_angela_white.mp4',
  },
  {
    id: ResourceNames.videoWomanLickAngelaWhiteOrgasm,
    type: 'video',
    tags: ['woman', 'lick', 'angela', 'white', 'orgasm'],
    path: '/assets/resources/new-game/video.woman_lick_angela_white_orgasm.mp4',
  },
  {
    id: ResourceNames.videoWomanLickTits,
    type: 'video',
    tags: ['woman', 'lick', 'tits'],
    path: '/assets/resources/new-game/video.woman_lick_tits.mp4',
  }
]
